//# APC Key25 buttons
export const BUTTONS = {
  BTN_SHIFT: 0x62,
  BTN_STOP_ALL_CLIPS: 0x51,
  BTN_PLAY: 0x5b,
  BTN_RECORD: 0x5d,
  BTN_TRACK_1: 0x40,
  BTN_UP: 0x40,
  BTN_TRACK_2: 0x41,
  BTN_DOWN: 0x41,
  BTN_TRACK_3: 0x42,
  BTN_LEFT: 0x42,
  BTN_UNDO: 0x42,
  BTN_TRACK_4: 0x43,
  BTN_RIGHT: 0x43,
  BTN_REDO: 0x43,
  BTN_TRACK_5: 0x44,
  BTN_KNOB_CTRL_VOLUME: 0x44,
  BTN_TRACK_6: 0x45,
  BTN_KNOB_CTRL_PAN: 0x45,
  BTN_TRACK_7: 0x46,
  BTN_KNOB_CTRL_SEND: 0x46,
  BTN_TRACK_8: 0x47,
  BTN_KNOB_CTRL_DEVICE: 0x47,
  BTN_SOFT_KEY_START: 0x52,
  BTN_SOFT_KEY_END: 0x56,
  BTN_SOFT_KEY_CLIP_STOP: 0x52,
  BTN_KNOB_1: 0x52,
  BTN_SOFT_KEY_SOLO: 0x53,
  BTN_KNOB_2: 0x53,
  BTN_SOFT_KEY_MUTE: 0x54,
  BTN_KNOB_3: 0x54,
  BTN_SOFT_KEY_REC_ARM: 0x55,
  BTN_KNOB_4: 0x55,
  BTN_SOFT_KEY_SELECT: 0x56,
  BTN_KNOB_5: 0x56,
  BTN_PAD_START: 0x00,
  BTN_PAD_END: 0x27,
  BTN_PAD_29: 0x1c,
  BTN_ALT: 0x1c,
  BTN_PAD_30: 0x1d,
  BTN_METRONOME: 0x1d,
  BTN_PAD_31: 0x1e,
  BTN_PAD_STEP: 0x1e,
  BTN_PAD_37: 0x24,
  BTN_OPT_ADMIN: 0x24,
  BTN_PAD_38: 0x25,
  BTN_MIX_LEVEL: 0x25,
  BTN_PAD_39: 0x26,
  BTN_CTRL_PRESET: 0x26,
  BTN_PAD_40: 0x27,
  BTN_ZS3_SHOT: 0x27,
  BTN_PAD_5: 0x04,
  BTN_PAD_LEFT: 0x04,
  BTN_PAD_6: 0x05,
  BTN_PAD_DOWN: 0x05,
  BTN_PAD_7: 0x06,
  BTN_PAD_RIGHT: 0x06,
  BTN_PAD_8: 0x07,
  BTN_F4: 0x07,
  BTN_PAD_13: 0x0c,
  BTN_BACK_NO: 0x0c,
  BTN_PAD_14: 0x0d,
  BTN_PAD_UP: 0x0d,
  BTN_PAD_15: 0x0e,
  BTN_SEL_YES: 0x0e,
  BTN_PAD_16: 0x0f,
  BTN_F3: 0x0f,
  BTN_PAD_21: 0x14,
  BTN_PAD_RECORD: 0x14,
  BTN_PAD_23: 0x16,
  BTN_PAD_PLAY: 0x16,
  BTN_PAD_24: 0x17,
  BTN_F2: 0x17,
  BTN_PAD_32: 0x1f,
  BTN_F1: 0x1f,
  // APC Key25 knobs
  KNOB_1: 0x30,
  KNOB_LAYER: 0x30,
  KNOB_2: 0x31,
  KNOB_SNAPSHOT: 0x31,
  KNOB_3: 0x32,
  KNOB_4: 0x33,
  KNOB_5: 0x34,
  KNOB_BACK: 0x34,
  KNOB_6: 0x35,
  KNOB_SELECT: 0x35,
  KNOB_7: 0x36,
  KNOB_8: 0x37,
};

// APC Key25 LED colors and modes
export const COLOR_DARK_GREY = 0x01,
  COLOR_RED = 0x05,
  COLOR_GREEN = 0x15,
  COLOR_BLUE = 0x25,
  COLOR_AQUA = 0x21,
  COLOR_BLUE_DARK = 0x2d,
  COLOR_BLUE_LIGHT = 0x24,
  COLOR_WHITE = 0x03,
  COLOR_EGYPT = 0x6c,
  COLOR_ORANGE = 0x09,
  COLOR_ORANGE_LIGHT = 0x08,
  COLOR_AMBER = 0x54,
  COLOR_RUSSET = 0x3d,
  COLOR_PURPLE = 0x51,
  COLOR_PINK = 0x39,
  COLOR_PINK_LIGHT = 0x52,
  COLOR_PINK_WARM = 0x38,
  COLOR_YELLOW = 0x0d,
  COLOR_LIME = 0x4b,
  COLOR_LIME_DARK = 0x11,
  COLOR_DARK_GREEN = 0x41,
  COLOR_GREEN_YELLOW = 0x4a,
  COLOR_BROWNISH_RED = 0x0a,
  COLOR_BROWN_LIGHT = 0x7e;

export const LED_OFF = 0x90,
  LED_BRIGHT_10 = 0x90,
  LED_BRIGHT_25 = 0x91,
  LED_BRIGHT_50 = 0x92,
  LED_BRIGHT_65 = 0x93,
  LED_BRIGHT_75 = 0x94,
  LED_BRIGHT_90 = 0x95,
  LED_BRIGHT_100 = 0x96,
  LED_PULSING_16 = 0x97,
  LED_PULSING_8 = 0x98,
  LED_PULSING_4 = 0x99,
  LED_PULSING_2 = 0x9a,
  LED_BLINKING_24 = 0x9b,
  LED_BLINKING_16 = 0x9c,
  LED_BLINKING_8 = 0x9d,
  LED_BLINKING_4 = 0x9e,
  LED_BLINKING_2 = 0x9f;


export const LED_BRIGHTS = [
        LED_BRIGHT_10,
        LED_BRIGHT_25,
        LED_BRIGHT_50,
        LED_BRIGHT_65,
        LED_BRIGHT_75,
        LED_BRIGHT_90,
        LED_BRIGHT_100,
      ];

export const SL_STATE_UNKNOWN = -1,
SL_STATE_OFF = 0,
SL_STATE_REC_STARTING = 1,
SL_STATE_RECORDING = 2,
SL_STATE_REC_STOPPING = 3,
SL_STATE_PLAYING = 4,
SL_STATE_OVERDUBBING = 5,
SL_STATE_MULTIPLYING = 6,
SL_STATE_INSERTING = 7,
SL_STATE_REPLACING = 8,
SL_STATE_DELAYING = 9,
SL_STATE_MUTED = 10,
SL_STATE_SCRATCHING = 11,
SL_STATE_PLAYING_ONCE = 12,
SL_STATE_SUBSTITUTING = 13,
SL_STATE_PAUSED = 14,
SL_STATE_UNDO_ALL = 15,
SL_STATE_TRIGGER_PLAY = 16,
SL_STATE_UNDO = 17,
SL_STATE_REDO = 18,
SL_STATE_REDO_ALL = 19,
SL_STATE_OFF_MUTED = 20;

export const SL_STATES = {
  [SL_STATE_UNKNOWN]: { name: "unknown", color: COLOR_DARK_GREY, ledmode: LED_OFF },
  [SL_STATE_OFF]: { name: "off", color: COLOR_WHITE, ledmode: LED_BRIGHT_100 },
  [SL_STATE_REC_STARTING]: {
    name: "waitstart",
    color: COLOR_RED,
    ledmode: LED_PULSING_16,
  },
  [SL_STATE_RECORDING]: {
    name: "record",
    color: COLOR_RED,
    ledmode: LED_BRIGHT_100,
  },
  [SL_STATE_REC_STOPPING]: {
    name: "waitstop",
    color: COLOR_RED,
    ledmode: LED_PULSING_8,
  },
  [SL_STATE_PLAYING]: {
    name: "play",
    color: COLOR_GREEN,
    ledmode: LED_BRIGHT_100,
  },
  [SL_STATE_OVERDUBBING]: {
    name: "overdub",
    color: COLOR_PURPLE,
    ledmode: LED_BRIGHT_100,
  },
  [SL_STATE_MULTIPLYING]: {
    name: "multiply",
    color: COLOR_AMBER,
    ledmode: LED_BRIGHT_100,
  },
  [SL_STATE_INSERTING]: {
    name: "insert",
    color: COLOR_PINK_WARM,
    ledmode: LED_BRIGHT_100,
  },
  [SL_STATE_REPLACING]: {
    name: "replace",
    color: COLOR_PINK_LIGHT,
    ledmode: LED_BRIGHT_100,
  },
  [SL_STATE_SUBSTITUTING]: {
    name: "substitute",
    color: COLOR_PINK,
    ledmode: LED_BRIGHT_100,
  },
  [SL_STATE_DELAYING]: { name: "delay", color: COLOR_RED, ledmode: LED_BRIGHT_10 },
  //  10: { name: "mute", color: COLOR_BLUE_DARK, ledmode: LED_BRIGHT_75 },
  [SL_STATE_MUTED]: {
    name: "mute",
    color: COLOR_DARK_GREEN,
    ledmode: LED_BRIGHT_100,
  },
  [SL_STATE_SCRATCHING]: {
    name: "scratch",
    color: COLOR_BLUE,          // @todo suitable color (rainbow?)
    ledmode: LED_BRIGHT_100,
  },
  [SL_STATE_PLAYING_ONCE]: {
    name: "oneshot",
    color: COLOR_LIME_DARK,
    ledmode: LED_PULSING_8,
  },
  [SL_STATE_PAUSED]: {
    name: "pause",
    color: COLOR_GREEN_YELLOW,
    ledmode: LED_BRIGHT_100,
  },
  [SL_STATE_UNDO_ALL]: {
    name: "undo_all",
    color: COLOR_DARK_GREY,
    ledmode: LED_BRIGHT_100,
  },
  [SL_STATE_UNDO]: {
    name: "undo_all",
    color: COLOR_DARK_GREY,
    ledmode: LED_BRIGHT_50,
  },
  [SL_STATE_REDO]: {
    name: "redo",
    color: COLOR_DARK_GREY,
    ledmode: LED_BRIGHT_50,
  },
  [SL_STATE_REDO_ALL]: {
    name: "redo_all",
    color: COLOR_DARK_GREY,
    ledmode: LED_BRIGHT_100,
  },
  [SL_STATE_OFF_MUTED]: {
    name: "offmute",
    color: COLOR_RED,
    ledmode: LED_BRIGHT_100,
  }, // undocumented
  [SL_STATE_TRIGGER_PLAY]: {
    name: "trigger_play",
    color: COLOR_GREEN,
    ledmode: LED_BRIGHT_100,
  }
};
